---
- name: Load vars (Install)
  ansible.builtin.include_tasks: load_vars.yml
  when:
    - _pkg is undefined

- name: Install packages
  ansible.builtin.package:
    name: "{{ _pkg }}"
    state: present
  with_items: "{{ _packages_to_install | default([]) }}"
  loop_control:
    loop_var: _pkg
