---
- name: Set OS related variables
  ansible.builtin.include_vars: "{{ _vars }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "defaults.yml"
  loop_control:
    loop_var: _vars
