---
- name: Display the cloud_localds variable
  ansible.builtin.debug:
    var:
      cloud_localds
  tags:
    - never
    - debug

- name: Install the cloud image util package
  ansible.builtin.include_tasks: install.yml
  tags:
    - install

- name: Fail if dest and hostname are not defined
  ansible.builtin.fail:
    msg:
      - "Sorry, I can't help without dest or a hostname."
  when:
    - cloud_localds.dest is not defined
    - cloud_localds.hostname is not defined

- name: Display the _provider
  ansible.builtin.debug:
    var:
      _provider
  tags:
    - never
    - debug

- name: Set _provider to cloud_localds.provider
  ansible.builtin.set_fact: 
    _provider:
      cloud_localds.provider
  when:
    - cloud_localds.provider is defined
  
- name: Set _provider to cloud_localds
  ansible.builtin.set_fact: 
    _provider:
      cloud_localds
  when:
    - _provider is not defined 

- name: Display the _provider
  ansible.builtin.debug:
    var:
      _provider
  tags:
    - never
    - debug

- name: Fail when config and config_template are defined
  ansible.builtin.fail:
    msg:
      - "Sorry, make up your mind."
      - "Use config or config_template"
  when:
    - cloud_localds.config is defined
    - cloud_localds.config_template is defined

- name: Fail when network_config and network_config_template are defined
  ansible.builtin.fail:
    msg:
      - "Sorry, make up your mind."
      - "Use network_config or network_config_template"
  when:
    - cloud_localds.network_config is defined
    - cloud_localds.network_config_template is defined

- name: Set _cloud_localds_dir to default
  ansible.builtin.set_fact:
    _cloud_localds_dir: "{{ _default_cloud_localds_dir }}"
  when: cloud_localds.dir is not defined

- name: Use the dest location
  when:
    cloud_localds.dest is defined
  block:
    - name: Set _cloudinit_iso
      ansible.builtin.set_fact:
        _cloudinit_iso:
          "{{ cloud_localds.dest }}"
    - name: Set _cloudinit_config
      ansible.builtin.set_fact:
        _cloudinit_config_yml:
          "{{ cloud_localds.dest }}_config.yml"
    - name: Set _cloudinit_net_config
      ansible.builtin.set_fact:
        _cloudinit_net_config_yml:
          "{{ cloud_localds.dest }}_net_config.yml"

- name: Use the hostname location
  when:
    cloud_localds.dest is not defined
  block:
    - name: Set _cloudinit_iso
      ansible.builtin.set_fact:
        _cloudinit_iso:
          "{{ _cloud_localds_dir }}/{{ cloud_localds.hostname }}_cloudinit.iso"
    - name: Set _cloudinit_config
      ansible.builtin.set_fact:
        _cloudinit_config_yml:
          "{{ _cloud_localds_dir }}/{{ cloud_localds.hostname }}_config.yml"
    - name: Set _cloudinit_net_config
      ansible.builtin.set_fact:
        _cloudinit_net_config_yml:
          "{{ _cloud_localds_dir }}/{{ cloud_localds.hostname }}_net_config.yml"

- name: Verify if _cloudinit_iso already exists
  ansible.builtin.stat:
    path: "{{ _cloudinit_iso }}"
  register:
    _cloudinit_iso_file

- name: Fail if dest already exists
  ansible.builtin.fail:
    msg: "Sorry, {{ _cloudinit_iso }} already exists"
  when:
    - _cloudinit_iso_file.stat.exists
    - not cloud_localds.overwrite|default(false)

# Create configs based on config
- name: Create config.yml based on cloud_localds.config
  ansible.builtin.copy:
    dest: "{{ _cloudinit_config_yml }}"
    content: "{{ cloud_localds.config }}"
    owner: "{{ cloud_localds.owner | default('0') }}"
    group: "{{ cloud_localds.group | default('0') }}"
    mode: "{{ cloud_localds.mode | default('0400') }}"
  when: cloud_localds.config is defined

- name: Create net_config.yml based on cloud_localds.network_config
  ansible.builtin.copy:
    dest: "{{ _cloudinit_net_config_yml }}"
    content: "{{ cloud_localds.network_config }}"
    owner: "{{ cloud_localds.owner | default('0') }}"
    group: "{{ cloud_localds.group | default('0') }}"
    mode: "{{ cloud_localds.mode | default('0400') }}"
  when: cloud_localds.network_config is defined

# Create config based on the templates
- name: Create config.yml based cloud_localds.config_template
  ansible.builtin.template:
    src: "{{ cloud_localds.config_template }}"
    dest: "{{ _cloudinit_config_yml }}"
    owner: "{{ cloud_localds.owner | default('0') }}"
    group: "{{ cloud_localds.group | default('0') }}"
    mode: "{{ cloud_localds.mode | default('0400') }}"
  when: cloud_localds.config_template is defined

- name: Create net_config.yml based on cloud_localds.network_config
  ansible.builtin.template:
    src: "{{ cloud_localds.network_config_template }}"
    dest: "{{ _cloudinit_net_config_yml }}"
    owner: "{{ cloud_localds.owner | default('0') }}"
    group: "{{ cloud_localds.group | default('0') }}"
    mode: "{{ cloud_localds.mode | default('0400') }}"
  when: cloud_localds.network_config_template is defined

- name: Execute the provider
  ansible.builtin.include_tasks: "{{ _provider_template }}"
  with_first_found:
    - "provider/{{ _provider }}.yml"
    - "provider/defaults.yml"
  loop_control:
    loop_var: _provider_template

- name: "Update file permissions"
  ansible.builtin.file:
    path: "{{ _cloudinit_iso }}"
    owner: "{{ cloud_localds.owner | default('0') }}"
    group: "{{ cloud_localds.group | default('0') }}"
    mode: "{{ cloud_localds.mode | default('0400') }}"
